[package]
name = "webauthn-rs-demo-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
webauthn-rs = { path = "../webauthn-rs", default-features = false }
