---
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
