all:
	cat test-data/register-start.json | cargo run -- --step register-start
	cat test-data/register-finish.json | cargo run -- --step register-finish
	cat test-data/authenticate-start.json | cargo run -- --step authenticate-start
	cat test-data/authenticate-finish.json | cargo run -- --step authenticate-finish
