all:
	cat test-data/register-start.json | cargo run -- --pretty-print register-start
	cat test-data/register-finish.json | cargo run -- --pretty-print register-finish
	cat test-data/authenticate-start.json | cargo run -- --pretty-print authenticate-start
	cat test-data/authenticate-finish.json | cargo run -- --pretty-print authenticate-finish
