[package]
name = "webauthn-attestation-ca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64urlsafedata.workspace = true
serde.workspace = true
tracing.workspace = true
openssl.workspace = true
uuid = { workspace = true, features = ["serde"] }
